### PR TITLE
v0.11.1

### PR DESCRIPTION
**Pull request by wantehchang**

### CODE REVIEW

**Comment by wantehchang** [comment]
@jzern @vigneshvg Please review.
@joedrago @y-guyon Just FYI.

libavif v0.11.1 is a patch release that fixes the build failures of our tests reported by Jan Beich (@jbeich) (https://github.com/AOMediaCodec/libavif/issues/1162 and https://github.com/AOMediaCodec/libavif/issues/1165) and a test failure if libsharpyuv is not found (https://github.com/AOMediaCodec/libavif/issues/1164).

**Review by vigneshvg — APPROVED** [review]

**Review by jzern — APPROVED** [review]

**Comment by jzern** [comment]
It looks like this should be held until #1174 and #1175 are assessed.

**Comment by wantehchang** [comment]
Yes, I will wait until after our team meeting tomorrow.

**Review by vigneshvg — APPROVED** [review]

**Comment by jzern** [comment]
lgtm

**Pull request merged**
