### PR TITLE
Pass correct src and dst strides to ScalePlane_12

### PR DESCRIPTION
**Pull request by wantehchang**
Fix https://github.com/AOMediaCodec/libavif/issues/715.

### CODE REVIEW

**Comment by joedrago** [comment]
Should those local stride variables be const?

**Comment by wantehchang** [comment]
I can declare the local stride variables as const. (I wasn't sure what your preference was.) Would you like me to declare the local planes variables as const for consistency? For example,

`uint8_t * const dstPlane = image->yuvPlanes[i];`

**Comment by joedrago** [comment]
Yes, I think so.

**Comment by wantehchang** [comment]
Done. Please review the new commit. Thanks.

**Pull request merged**
