### PR TITLE
Properly check for cache hits.

### PR DESCRIPTION
**Pull request by vrabaud**
`steps.cache-ext.outputs.cache-hit != 'true'` is actually always true because `steps.cache-ext.outputs.cache-hit` does not exist anymore, as the step `cache-hit` is now hidden in the cache action. The `cache-hit` information has to be sent back from the cache action.

### CODE REVIEW

**Review by y-guyon — APPROVED** [review]
I am surprised this change is needed, it was working as is at some point.

**Review by wantehchang — CHANGES_REQUESTED** [review]
Vincent: Searching for "cache-hit" in https://github.com/actions/cache, I found that we are testing `cache-hit` in the same way as the sample code.

Are you sure this pull request is necessary?

**Comment by vrabaud** [comment]
Let's put this one on the back burner, maybe I thgought it was necessary because of a cache miss.

**Comment by vrabaud** [comment]
The cache hit was not checked properly: the answer from the action has to be sent back to the main workflow.

**Review by y-guyon — APPROVED** [review]

**Pull request merged**
