### PR TITLE
Add CIFuzz

### PR DESCRIPTION
**Pull request by Leo-Neat**
OSS-Fuzz was wondering if libavif would use CIFuzz, a new feature being rolled out
in OSS-Fuzz. It allows for pull requests to be fuzzed in CI using fuzz targets enabled
in OSS-Fuzz. Documentation for this feature can be found at https://google.github.io/oss-fuzz/getting-started/continuous-integration/
Let us know if you have any questions!

### CODE REVIEW

**Comment by joedrago** [comment]
I'm definitely on board with this change/feature, but it looks like it is failing to build dav1d because it can't find nasm, despite it being built and available in the previous step. 

I'm not familiar with this fuzz.yml mechanism -- is this building exactly the same way oss-fuzz builds, or is there some oddity here?

**Comment by Leo-Neat** [comment]
@joedrago Ill look into the build failure.

**Comment by Leo-Neat** [comment]
@joedrago  What happens is we mount the checked out PR over the previous state and delete contents not in the checked out PR. This removes some of your files necessary for building. So the issue is on our end and I am working to patch it. Should have one up soon!

**Comment by joedrago** [comment]
@Leo-Neat Any movement on this one? If your interest in adding this isn't there anymore, can I close this PR?

**Pull request closed without merging**
