### PR TITLE
Ext: Update to SVT-AV1 v2.0.0

### PR DESCRIPTION
**Pull request by wantehchang**

### CODE REVIEW

**Comment by wantehchang** [comment]
@hassount @1480c1 Hassene and Christopher: The current [libavif/src/codec_svt.c](https://github.com/AOMediaCodec/libavif/blob/main/src/codec_svt.c) compiles successfully with SVT-AV1 v2.0.0, but I am wondering if we should make a change similar to https://github.com/FFmpeg/FFmpeg/commit/69dd1ce610fcffec453a0663c613c9b13165fd9e, or any other change to take advantage of SVT-AV1 v2.0.0. Could you please take a look? Thanks.

**Review by y-guyon — APPROVED** [review]

**Comment by hassount** [comment]
@wantehchang apologies for the delay on this. I believe the way it is right now is ok, but let me get another set of eyes just to make sure. in the mean time, can you check that a 3 frame encode for example with libavif would produce 3 frames at the output side and not 2 >?

**Comment by wantehchang** [comment]
@hassount Hassene: I tested with the following commands:

```
./avifenc --codec svt peach.jpg peach.jpg peach.jpg peach-3.avif
./avifdec --info peach-3.avif
./avifdec --index 0 peach-3.avif out0.y4m
./avifdec --index 1 peach-3.avif out1.y4m
./avifdec --index 2 peach-3.avif out2.y4m
./avifdec --index 3 peach-3.avif out3.y4m
```

`./avifdec --info peach-3.avi` reported that the image sequence has three frames.

And only `./avifdec --index 3 peach-3.avif out3.y4m` failed as expected.

**Comment by wantehchang** [comment]
I repeated my test with different input images (rather than repeating an input image three times).

```
./avifenc --codec svt --yuv 420 kodim01.png kodim02.png kodim03.png kodim01-03.avif
./avifdec --info kodim01-03.avif
./avifdec --index 0 kodim01-03.avif out0.png
./avifdec --index 1 kodim01-03.avif out1.png
./avifdec --index 2 kodim01-03.avif out3.png
./avifdec --index 3 kodim01-03.avif out3.png
```

**Comment by hassount** [comment]
Excellent, thank you!, I see in the code that you’re sending the EOS as soon as you receive the last packet. This LGTM and is ok for me to proceed.

**Comment by wantehchang** [comment]
Thanks a lot for the review!

**Pull request merged**
