### PR TITLE
Do not set CMAKE_C_COMPILER and CMAKE_CXX_COMPILER

### PR DESCRIPTION
**Pull request by wantehchang**
See https://google.github.io/oss-fuzz/getting-started/new-project-guide/#Requirements

Passing the -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ options to cmake ignores the CC and CXX environment variables set by oss-fuzz.

### CODE REVIEW

**Comment by vrabaud** [comment]
I confirm it now all builds fine with afl compiler

**Review by vrabaud — APPROVED** [review]

**Comment by wantehchang** [comment]
Vincent: Thank you for testing this pull request.

**Comment by wantehchang** [comment]
Vincent: How do I build with the afl compiler?

**Comment by vrabaud** [comment]
You can specify the engine when building the fuzzers: `python3 infra/helper.py build_fuzzers --engine afl libavif`

**Pull request merged**
