### PR TITLE
Some fixes to cmake and support for find_package(libavif)

### PR DESCRIPTION
**Pull request by cryptomilk**
Here are some fixes for cmake and config files so other projects can find it using:

`find_package(libavif 0.4.7)`

### CODE REVIEW

**Comment by cryptomilk** [comment]
I just checked for sanity as the libaom on my system is 1.0.0 and it is not compatible with libavif.

Also for compiler flag checking you should do it in a way that all compilers are supported. See e.g.

https://gitlab.com/cmocka/cmocka/blob/master/CompilerChecks.cmake

**Comment by cryptomilk** [comment]
Took some iterations to fix appveyor but everything is green now.

**Comment by joedrago** [comment]
There are some fantastic changes here. The only one I'm unsure on is enforcing BUILD_SHARED_LIBS. As I mentioned in my recent commit removing STATIC from add_library, I'd prefer to stay un-opinionated and leave CMake's defaults here.  Are there distro packaging concerns you have if that line is removed?

**Comment by cryptomilk** [comment]
Normally you want shared libs by default. It makes sense resource wise and security wise.

**Comment by joedrago** [comment]
Hmm, alright. I'm on board with shared-by-default, but I don't want to have libavif change a cmake option default, so I'll remove that line and make `AVIF_BUILD_STATIC` do more work. Starting the merge now.

**Comment by darix** [comment]
distro people like cryptomilk and me prefer shared libraries :)

**Comment by joedrago** [comment]
Alright, I merged in your changes and then reworked some of the static-vs-shared stuff a bit. The important takeaway is that it is still shared by default, and all of the find_package stuff survived my tweaking without any changes. I'm going to bump the libavif version soon, so you'll be able to use that new version number for whatever packaging scripts you've got cooking.

Keep those distro-packaging-related PRs coming! I don't claim to be an expert in that specific kind of voodoo, and I'm all for wider adoption.

**Comment by joedrago** [comment]
`v0.4.8` is pushed and has the goods.

**Comment by cryptomilk** [comment]
Normally projects set BUILD_SHARED_LIBS as an option. This is meant that way, see also the documentation for it https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

**Comment by joedrago** [comment]
Oh, I didn't realize it was recommended / common practice to include your own default for it. I figured it would virally pollute parent CMake projects if a library project was added as a child project. 

I'll do some local testing and possibly reintroduce that to my CMakeLists, but seeing as functionally we've arrived at the same default behavior, this should no longer be a blocker, right?

**Pull request merged**
