### PR TITLE
tests: Replace {true, false} with ::testing::Bool()

### PR DESCRIPTION
**Pull request by vigneshvg**

### CODE REVIEW

**Review by wantehchang — CHANGES_REQUESTED** [review]
Thank you for the pull request. I request two changes.

We should only replace `Values(false, true)` or `Values(true, false)` with `Bool()`.

**Review by wantehchang — APPROVED** [review]
LGTM.

The commit message says "tests: Replace {true, false} with ::testing::Bool() #1312". It probably should be updated to say Values(false, true) instead, although it seems challenging to stay under 50 characters.

**Comment by vigneshvg** [comment]
> LGTM.
> 
> The commit message says "tests: Replace {true, false} with ::testing::Bool() #1312". It probably should be updated to say Values(false, true) instead, although it seems challenging to stay under 50 characters.

I just replaced the true, false with false,true in the commit msg. I think that's fine.

**Comment by vigneshvg** [comment]
> My previous comment was not clear. I meant that `{false, true}` is not the same as `Values(false, true)`, so the commit message could be more precise, but I am afraid that will exceed the 50-character limit.

Ah okay got it. Yeah, that would be hard to fit in 50 chars.

**Pull request merged**
