### PR TITLE
Update the version to 1.0.4 (devel flag on)

### PR DESCRIPTION
**Pull request by y-guyon**
See #1850 for the corresponding pull request for the libavif 1.0.3 release.

### CODE REVIEW

**Review by wantehchang — APPROVED** [review]
LGTM. Thanks.

**Review by wantehchang — COMMENTED** [review]
LGTM except for the duplicate bug number (b/321189607).

**Comment by y-guyon** [comment]
> LGTM except for the duplicate bug number (b/321189607).

Done in https://github.com/AOMediaCodec/libavif/pull/1990 and https://github.com/AOMediaCodec/libavif/pull/1991

**Comment by y-guyon** [comment]
Branch `v1.0.x` updated in https://github.com/AOMediaCodec/libavif/pull/1979 and https://github.com/AOMediaCodec/libavif/pull/1980.

**Pull request merged**
