### PR TITLE
Ext: Update to SVT-AV1 v0.8.7

### PR DESCRIPTION
**Pull request by EwoutH**
Update SVT-AV1 in scripts from v0.8.6 to [v0.8.7](https://gitlab.com/AOMediaCodec/SVT-AV1/-/releases/v0.8.7).

### CODE REVIEW

**Review by wantehchang — APPROVED** [review]
LGTM. Thanks!

**Comment by joedrago** [comment]
That changelog entry is in the wrong place. I'll fix it.

**Comment by joedrago** [comment]
https://github.com/AOMediaCodec/libavif/commit/83d597c9754b0a7b950dab944ac89b2d0c10333b

**Comment by EwoutH** [comment]
> That changelog entry is in the wrong place. I'll fix it.

I think that happened because this PR was opened before the 0.9.1 tag. Thanks for fixing it!

**Pull request merged**
