### PR TITLE
CMake: Set flags based if the compiler supports it rather than by name

### PR DESCRIPTION
**Pull request by 1480c1**
This should help with setting generic cflags for those that do support them

https://cmake.org/cmake/help/v3.5/module/CheckCCompilerFlag.html

### CODE REVIEW

**Comment by cryptomilk** [comment]
The right thing would be to test if they are supported by the compiler, see e.g.

https://gitlab.com/cmocka/cmocka/-/blob/master/CompilerChecks.cmake

**Comment by 1480c1** [comment]
I'm not sure if you are expressing disapproval, approval, or just stating something? Your message seems a bit... cryptic (lol)

But either way, this pr does change it to use `check_c_compiler_flag` https://github.com/AOMediaCodec/libavif/pull/242/files#diff-af3b638bc2a3e6c650974192a53c7291R126

**Comment by joedrago** [comment]
I'd prefer to not take this one, honestly. I think this will slow down CMake generation time and create a whole new set of compile combinations I'm going to have to support. I'd rather occasionally hit an issue with a specific build env and directly target a fix for it.

**Comment by wantehchang** [comment]
I think we can close this pull request. Most of those compiler warning flags are known to be supported by the versions of Clang, GCC, and MSVC that we need to support, so we don't need to detect their presence at build time. We should take advantage of the knowledge and save time.

**Pull request closed without merging**
