### PR TITLE
Add the --no-strict-pixi option to avifdec

### PR DESCRIPTION
**Pull request by wantehchang**
Add an easy way to verify that the missing pixi property is the only
problem with an AVIF image.

### CODE REVIEW

**Comment by wantehchang** [comment]
Joe: If you think this option is not generally useful, please feel free to reject this PR. Thanks!

**Comment by joedrago** [comment]
Hmm. I guess this change is fine, but I'm curious when it is used? We already print out a very clear diagnostic error when the reason an image fails is because of pixi (or any other `[Strict]` check).

**Comment by wantehchang** [comment]
Joe: Since avifdec stops parsing after the pixi check fails, one cannot tell if the image has other problems. This option allows us to check if the missing pixi property is the only problem.

**Comment by joedrago** [comment]
My only remaining comment would be that this feels very specific / incomplete. Should we have `--no-strict-*` for all strict flags? It seems weird to single out this specific flag as a commandline switch.

**Comment by wantehchang** [comment]
Because not all strict checks are equal. Because libheif is used in two popular image tools (libvips, used by other libraries, and ImageMagick), the missing pixi property problem is encountered much more often.

I don't mind making this change manually when I need to debug this kind of problem though. If you think this option could be confusing, I can close this PR.

**Comment by joedrago** [comment]
I think if it benefits your workflow, we can add it. Based on other conversations though, I could see this specific flag being deprecated at some point and this new switch being moot.

**Comment by wantehchang** [comment]
I am going to close this pull request. I can make the `strictFlags &= ~AVIF_STRICT_PIXI_REQUIRED` change when I need it.

**Pull request closed without merging**
