### PR TITLE
Add GitHub Actions workflow for Windows builds

### PR DESCRIPTION
**Pull request by aosoft**
* Build applications (avifdec.exe, avifenc.exe) and libs (avif_static.lib)
* Build shared libraries (avif.dll)
* Support feature switches (aom, dav1d, rav1e, libgav1, svt, libyuv)

### CODE REVIEW

**Comment by tongyuantongyu** [comment]
We probably don't want to hardcode dependency versions in CI config file.
meson can be installed through pip.
libyuv has some trouble building with Ninja generator and MSVC compiler. We may fix it in `libyuv.cmd` directly.

**Comment by aosoft** [comment]
Thanks for reply.

>meson can be installed through pip.

On Windows, when meson was installed by pip, it could not be executed by meson command, so I got it from GitHub.
https://stackoverflow.com/questions/42712896/how-to-run-meson-build-system-on-windows

**Comment by tongyuantongyu** [comment]
> On Windows, when meson was installed by pip, it could not be executed by meson command, so I got it from GitHub.

It should work if the `Scripts` folder of your active python environment is in your `PATH` environment variable. 
Github Action's environment has this set up, so you can install it using pip.

I made some changes on your commits here: https://github.com/tongyuantongyu/libavif/commits/build-windows-action . If you think these changes are good, feel free to cherry pick them into your branch.

**Comment by aosoft** [comment]
> > On Windows, when meson was installed by pip, it could not be executed by meson command, so I got it from GitHub.
> 
> It should work if the `Scripts` folder of your active python environment is in your `PATH` environment variable.
> Github Action's environment has this set up, so you can install it using pip.
> 
> I made some changes on your commits here: https://github.com/tongyuantongyu/libavif/commits/build-windows-action . If you think these changes are good, feel free to cherry pick them into your branch.

Thank you for the fix. I've confirmed that I can build it.
When I was trying, installing meson with pip failed to build even on GitHub Actions, so I had that implementation.

**Comment by vrabaud** [comment]
There is now Windows CI, so closing.

**Pull request closed without merging**
