### PR TITLE
Remove alphaRange from avifImage

### PR DESCRIPTION
**Pull request by vigneshvg**
The AVIF draft specification disallows limited range alpha and it
will eventually be in the specification once AOM ratifies it [1] [2].

Even though the default value of alphaRange is set to
AVIF_RANGE_FULL, it is possible for applications to override it
and set it to AVIF_RANGE_LIMITED thereby producing AVIF images
that will eventually be invalid.

On the encoder side, This PR prevents such images from being
produced by libavif.

On the decoder side, if we encounter an image with limited range
alpha, we always convert it to full range alpha and the applications
can assume that alpha plane is always in full range (as it will be
required by the spec eventually).

This change breaks the ABI and a note has been added to CHANGELOG.md
in the "Unreleased" section to document that.

[1] https://github.com/AOMediaCodec/av1-avif/pull/101
[2] https://aomediacodec.github.io/av1-avif/#auxiliary-images

### CODE REVIEW

**Comment by jzern** [comment]
lgtm. Just one update for the commit message: Eventhough -> Even though...

**Review by wantehchang — APPROVED** [review]
LGTM. Thanks. I made some minor edits in src/read.c.

**Comment by Jamaika1** [comment]
I cann't merge libavif in libwebp2.
c:/msys1201/bin/../lib/gcc/x86_64-w64-mingw32/12.0.1/../../../../x86_64-w64-mingw32/bin/ld.exe: avif\read.o:read.c:(.text+0x32df): undefined reference to `avifLimitedToFullY'
c:/msys1201/bin/../lib/gcc/x86_64-w64-mingw32/12.0.1/../../../../x86_64-w64-mingw32/bin/ld.exe: avif\read.o:read.c:(.text+0x33f8): undefined reference to `avifLimitedToFullY'
collect2.exe: error: ld returned 1 exit status

**Comment by vigneshvg** [comment]
> I cann't merge libavif in libwebp2. c:/msys1201/bin/../lib/gcc/x86_64-w64-mingw32/12.0.1/../../../../x86_64-w64-mingw32/bin/ld.exe: avif\read.o:read.c:(.text+0x32df): undefined reference to `avifLimitedToFullY' c:/msys1201/bin/../lib/gcc/x86_64-w64-mingw32/12.0.1/../../../../x86_64-w64-mingw32/bin/ld.exe: avif\read.o:read.c:(.text+0x33f8): undefined reference to `avifLimitedToFullY' collect2.exe: error: ld returned 1 exit status

I didn't try the windows build after this patch. I will take a look at this issue.

**Comment by jzern** [comment]
@Jamaika1 Thanks for the report. I'm not able to reproduce the issue under msys2 with a gcc 11.3.0 toolchain. Can you give the set of commands you're using?

**Comment by Jamaika1** [comment]
I use gcc 12.0.1 20220429. http://msystem.waw.pl/x265/mingw-gcc1201-20220429.7z
I use plugins for gcc thread/mutex/future/condition_variable
https://github.com/Jamaika1/mingw_std_threads

opensource libwebp2
https://www.sendspace.com/file/z639jj

**Comment by jzern** [comment]
Thanks, can you share the cmake commands you used?

> I use gcc 12.0.1 20220429. http://msystem.waw.pl/x265/mingw-gcc1201-20220429.7z I use plugins for gcc thread/mutex/future/condition_variable https://github.com/Jamaika1/mingw_std_threads
> 
> opensource libwebp2 https://www.sendspace.com/file/z639jj

I used https://chromium.googlesource.com/codecs/libwebp2, I'm assuming the rar is a copy of that.

**Comment by Jamaika1** [comment]
RAR is a copy of that and plugins. You create codec via .bat file.

**Comment by jzern** [comment]
The batch file has include path issues, which are easily fixed and then runs into a command line length limitation. I would suggest using cmake to build the intermediate libraries rather than listing all of the .o's manually. In this change use of avifLimitedToFullY was added to read.c, but you may be missing reformat.o in one or more of your command lines.

**Comment by Jamaika1** [comment]
Nothing is missing. As you compiled what I put in rar, you can see that the avifenc/dec file is creating and rd_curve/libwebp2 is not.

**Comment by jzern** [comment]
I didn't mean anything was missing, just that the compile failed with webp2.bat as it was. There's a pattern like 'cd dir; for ... gcc' this needed to add -I<top-level>/include. Later the link would fail in a command prompt due to overlong command lines. Either way, I suggest checking the .o's in the link line or switching to building the intermediate libraries with cmake, which works for me.

**Comment by Jamaika1** [comment]
At first it will fail.
You need to copy the GCC to the msys1201 directory on the C drive and save it to a bat file
some files from rar include you need to copy to gcc msys1201\x86_64-w64-mingw32\include
the second files from rar include must be copied to gcc msys1201\include\c ++\12.0.1
It should work.

**Comment by jzern** [comment]
Those aren't the includes I was referring to, I meant the include path to files like aom_config.h, etc. Since you cd into the directories the top-level paths aren't visible without adding -I<top-level>/include to the command lines in the batch file.

As for the object files I mentioned, if you look at the command lines that produce rd_curve.exe and av1enc.exe they have avif\read.o (which uses `avifLimitedToFullY` as of this change), but do not have avif\reformat.o (which defines the function). avifdec.exe does have this and I'm assuming links all right.

**Pull request merged**
