### PR TITLE
Check for scale values that cause overflow

### PR DESCRIPTION
**Pull request by FrankGalligan**
This addresses #734

### CODE REVIEW

**Comment by joedrago** [comment]
A few observations:

* Don't we need to do similar checks for height? Or is this issue with libyuv fixed point math only width-related?
* Style: Can you change your `snake_case` variable names to `camelCase` for consistency? (`fixedPointDiv`, `maxFixedValue`)

**Comment by FrankGalligan** [comment]
I didn't add a check for height because the code is different and looks to have a check that might address it. I'm actually hoping this can be fixed better in libyuv, I just don't know the code that well to make a "fix" there.  If you want I can add the same check for height, I don't think it would hurt as it will perform the same scaling.

As for the `snake_case`, my bad I should have looked more in the file first.

**Comment by joedrago** [comment]
I'm also not familiar enough with libyuv's internals, but if it works entirely in fixed point for dimensions, I think putting a height check here would be good. We can always relax these restrictions by libyuv version if it gains support for larger sizes.

**Comment by FrankGalligan** [comment]
ok sounds good

**Comment by FrankGalligan** [comment]
I also asked that question of libyuv author, will see what they say.

**Pull request merged**
