### PR TITLE
Bump fuzztest

### PR DESCRIPTION
**Pull request by vrabaud**
BUG=oss-fuzz:66560
b/324876907

### CODE REVIEW

**Review by y-guyon — APPROVED** [review]

**Review by wantehchang — APPROVED** [review]
LGTM. Thanks!

**Comment by wantehchang** [comment]
Hi Vincent,

I verified that this pull request broke the command to reproduce an oss-fuzz bug locally. Here is an example of the error:

```
$ python infra/helper.py reproduce libavif avif_fuzztest_dec@DecodeAvifTest.Decode ~/Downloads/clusterfuzz-testcase-minimized-avif_fuzztest_dec\@DecodeAvifTest.Decode-5086614009217024 
INFO:__main__:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e HELPER=True -e ARCHITECTURE=x86_64 -v /usr/local/google/home/wtc/tmp/oss-fuzz-66755/oss-fuzz/build/out/libavif:/out -v /usr/local/google/home/wtc/Downloads/clusterfuzz-testcase-minimized-avif_fuzztest_dec@DecodeAvifTest.Decode-5086614009217024:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce avif_fuzztest_dec@DecodeAvifTest.Decode -runs=100.
+ FUZZER=avif_fuzztest_dec@DecodeAvifTest.Decode
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer avif_fuzztest_dec@DecodeAvifTest.Decode -runs=100 /testcase
/out/avif_fuzztest_dec@DecodeAvifTest.Decode -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase < /dev/null
Reading seeds from /out/corpus (non recursively)
Returning 36 seed images
ERROR: Unknown command line flag 'timeout'
ERROR: Unknown command line flag 'runs'. Did you mean: fuzz ?
```

Could you please take a look? Thanks.

**Comment by vrabaud** [comment]
So this is due to https://github.com/google/fuzztest/pull/959
Not sure why though: probably gtest that now does not allow some flags.
I tried removing the flags and it times out locally.
I have tried to modify those arguments on the fly too (replacing `timeout` by `fuzz_for` for example):
```
export ARGS=\$*
ARGS=`sed "s/-timeout=\\([0-9]\\+\\)/--fuzz_for=\1s/g" \${ARGS}`
ARGS="${ARGS/-seed=1337/}"
ARGS="${ARGS/-runs=4/}"
\$this_dir/$fuzz_basename --fuzz=$fuzz_entrypoint -- \${ARGS}
```
but I could not get it to work yet. As the fuzztest builds are broken, the safest is to revert to an older fuzztest version for now.

**Comment by wantehchang** [comment]
Vincent: Thank you very much for tracking this down. Should we report this issue to someone on the FuzzTest or oss-fuzz team?

**Pull request merged**
