### PR TITLE
pkgconf: Add private libraries in Requires.private for static linking

### PR DESCRIPTION
**Pull request by Biswa96**
@kmilos @1480c1 @mechakotik

### CODE REVIEW

**Comment by vrabaud** [comment]
Thx. How do you choose the libs to link to? Why not libyuv?

**Comment by Biswa96** [comment]
> How do you choose the libs to link to?

* For shared linking:

```
$ pkgconf -libs libavif
-lavif
```

* For static linking:

```
$ pkgconf -libs -static libavif
-lavif -lsharpyuv -ldav1d -lrav1e -lkernel32 -ladvapi32 -lbcrypt -lkernel32 -lntdll -luserenv -lws2_32 -lkernel32 -lws2_32 -lkernel32 -lSvtAv1Enc -laom -lm
```

> Why not libyuv?

libyuv does not provide any pkgconfig file. So, it can not be added in Requires.private but could be added in Libs.private. I was not sure about the later one - will be added in next commit.

**Comment by vrabaud** [comment]
Thx, makes sense.

**Comment by fdintino** [comment]
These libraries should be omitted from Requires.private and Libs.private if they are local, since in that case they get included in the archive file. If someone else doesn't get around to addressing that I'll open a PR myself next week to fix that.

**Comment by Biswa96** [comment]
Sure, please create a PR. I did not find the conditions for local dependencies.

**Pull request merged**
